test:default:
  image: louisvernon/lanlgcc48
  script:
    - sudo -E apt-get -y install gfortran
    - sudo -E apt-get -y install libblas-dev liblapack-dev
    - sudo -E apt-get -y install python3 python3-pip
    - pip3 install numpy scipy matplotlib
    - pip3 install spacepy
    - make 
    - ./ptm 1
