image: drsteve1663/lanlptm:1.0

stages:
  - ptmfunc
  - ptmprec

test:default:
  stage: ptmfunc
  script:
    - shopt -s expand_aliases
    - alias python='python3'
    - make 
    - ./ptm 1

test:dipole:
  stage: ptmprec
  script:
    - shopt -s expand_aliases
    - alias python='python3'
    - make 
    - python ptm_python/ptm_test_data.py

test:python:
  stage: ptmprec
  script:
    - shopt -s expand_aliases
    - alias python='python3'
    - make python
    - python ptm_python/test_ptm.py

test:regress1:
  stage: ptmprec
  script:
    - shopt -s expand_aliases
    - alias python='python3'
    - make ptm
    - ./ptm 1
    - cmp ptm_output/ptm_0001.dat ptm_output/ptm_0001.expected
